export default {
  location: {
    name: "Qom",
    region: "Qom",
    country: "Iran",
    lat: 34.6401,
    lon: 50.8764,
    tz_id: "Asia/Tehran",
    localtime_epoch: 1741875563,
    localtime: "2025-03-13 17:49",
  },
  current: {
    last_updated_epoch: 1741875300,
    last_updated: "2025-03-13 17:45",
    temp_c: 19.3,
    temp_f: 66.8,
    is_day: 1,
    condition: {
      text: "Sunny",
      icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
      code: 1000,
    },
    wind_mph: 3.4,
    wind_kph: 5.4,
    wind_degree: 349,
    wind_dir: "N",
    pressure_mb: 1018,
    pressure_in: 30.06,
    precip_mm: 0,
    precip_in: 0,
    humidity: 29,
    cloud: 0,
    feelslike_c: 19.3,
    feelslike_f: 66.8,
    windchill_c: 19.3,
    windchill_f: 66.8,
    heatindex_c: 19.3,
    heatindex_f: 66.8,
    dewpoint_c: 0.8,
    dewpoint_f: 33.4,
    vis_km: 10,
    vis_miles: 6,
    uv: 0.1,
    gust_mph: 4.2,
    gust_kph: 6.7,
  },
  forecast: {
    forecastday: [
      {
        date: "2025-03-13",
        date_epoch: 1741824000,
        day: {
          maxtemp_c: 19.8,
          maxtemp_f: 67.6,
          mintemp_c: 11.3,
          mintemp_f: 52.4,
          avgtemp_c: 16,
          avgtemp_f: 60.8,
          maxwind_mph: 5.6,
          maxwind_kph: 9,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 39,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 1.4,
        },
        astro: {
          sunrise: "06:20 AM",
          sunset: "06:12 PM",
          moonrise: "05:31 PM",
          moonset: "05:55 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: 98,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1741811400,
            time: "2025-03-13 00:00",
            temp_c: 14.4,
            temp_f: 57.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 46,
            cloud: 13,
            feelslike_c: 14.3,
            feelslike_f: 57.7,
            windchill_c: 14.3,
            windchill_f: 57.7,
            heatindex_c: 14.4,
            heatindex_f: 57.9,
            dewpoint_c: 2.9,
            dewpoint_f: 37.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.4,
            uv: 0,
          },
          {
            time_epoch: 1741815000,
            time: "2025-03-13 01:00",
            temp_c: 13.9,
            temp_f: 57,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 284,
            wind_dir: "WNW",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 47,
            cloud: 10,
            feelslike_c: 13.5,
            feelslike_f: 56.3,
            windchill_c: 13.5,
            windchill_f: 56.3,
            heatindex_c: 13.9,
            heatindex_f: 57,
            dewpoint_c: 2.8,
            dewpoint_f: 37,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.1,
            gust_kph: 16.3,
            uv: 0,
          },
          {
            time_epoch: 1741818600,
            time: "2025-03-13 02:00",
            temp_c: 13.3,
            temp_f: 56,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 48,
            cloud: 10,
            feelslike_c: 12.7,
            feelslike_f: 54.9,
            windchill_c: 12.7,
            windchill_f: 54.9,
            heatindex_c: 13.3,
            heatindex_f: 56,
            dewpoint_c: 2.7,
            dewpoint_f: 36.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.8,
            gust_kph: 17.4,
            uv: 0,
          },
          {
            time_epoch: 1741822200,
            time: "2025-03-13 03:00",
            temp_c: 12.8,
            temp_f: 55,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 50,
            cloud: 10,
            feelslike_c: 12.2,
            feelslike_f: 53.9,
            windchill_c: 12.2,
            windchill_f: 53.9,
            heatindex_c: 12.8,
            heatindex_f: 55,
            dewpoint_c: 2.6,
            dewpoint_f: 36.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.4,
            gust_kph: 16.8,
            uv: 0,
          },
          {
            time_epoch: 1741825800,
            time: "2025-03-13 04:00",
            temp_c: 12.2,
            temp_f: 53.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 51,
            cloud: 10,
            feelslike_c: 11.6,
            feelslike_f: 53,
            windchill_c: 11.6,
            windchill_f: 53,
            heatindex_c: 12.2,
            heatindex_f: 53.9,
            dewpoint_c: 2.4,
            dewpoint_f: 36.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.5,
            gust_kph: 15.3,
            uv: 0,
          },
          {
            time_epoch: 1741829400,
            time: "2025-03-13 05:00",
            temp_c: 11.6,
            temp_f: 52.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 52,
            cloud: 8,
            feelslike_c: 11.4,
            feelslike_f: 52.5,
            windchill_c: 11.4,
            windchill_f: 52.5,
            heatindex_c: 11.6,
            heatindex_f: 52.9,
            dewpoint_c: 2.1,
            dewpoint_f: 35.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12.1,
            uv: 0,
          },
          {
            time_epoch: 1741833000,
            time: "2025-03-13 06:00",
            temp_c: 11.3,
            temp_f: 52.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 267,
            wind_dir: "W",
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 52,
            cloud: 8,
            feelslike_c: 11.6,
            feelslike_f: 52.9,
            windchill_c: 11.6,
            windchill_f: 52.9,
            heatindex_c: 11.3,
            heatindex_f: 52.4,
            dewpoint_c: 2,
            dewpoint_f: 35.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.2,
            gust_kph: 8.3,
            uv: 0,
          },
          {
            time_epoch: 1741836600,
            time: "2025-03-13 07:00",
            temp_c: 13,
            temp_f: 55.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 266,
            wind_dir: "W",
            pressure_mb: 1021,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 49,
            cloud: 8,
            feelslike_c: 13.5,
            feelslike_f: 56.2,
            windchill_c: 13.5,
            windchill_f: 56.2,
            heatindex_c: 13,
            heatindex_f: 55.4,
            dewpoint_c: 2.6,
            dewpoint_f: 36.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 0.5,
          },
          {
            time_epoch: 1741840200,
            time: "2025-03-13 08:00",
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 293,
            wind_dir: "WNW",
            pressure_mb: 1022,
            pressure_in: 30.17,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 42,
            cloud: 7,
            feelslike_c: 15.3,
            feelslike_f: 59.6,
            windchill_c: 15.3,
            windchill_f: 59.6,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            dewpoint_c: 1.9,
            dewpoint_f: 35.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 1.5,
          },
          {
            time_epoch: 1741843800,
            time: "2025-03-13 09:00",
            temp_c: 15.8,
            temp_f: 60.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 310,
            wind_dir: "NW",
            pressure_mb: 1022,
            pressure_in: 30.17,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 39,
            cloud: 5,
            feelslike_c: 15.8,
            feelslike_f: 60.5,
            windchill_c: 15.8,
            windchill_f: 60.5,
            heatindex_c: 15.8,
            heatindex_f: 60.5,
            dewpoint_c: 1.8,
            dewpoint_f: 35.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 3.1,
          },
          {
            time_epoch: 1741847400,
            time: "2025-03-13 10:00",
            temp_c: 16.8,
            temp_f: 62.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 320,
            wind_dir: "NW",
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 4,
            feelslike_c: 16.9,
            feelslike_f: 62.3,
            windchill_c: 16.9,
            windchill_f: 62.3,
            heatindex_c: 16.9,
            heatindex_f: 62.3,
            dewpoint_c: 1.8,
            dewpoint_f: 35.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 4.7,
          },
          {
            time_epoch: 1741851000,
            time: "2025-03-13 11:00",
            temp_c: 17.7,
            temp_f: 63.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 333,
            wind_dir: "NNW",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 34,
            cloud: 4,
            feelslike_c: 17.7,
            feelslike_f: 63.9,
            windchill_c: 17.7,
            windchill_f: 63.9,
            heatindex_c: 17.7,
            heatindex_f: 63.9,
            dewpoint_c: 1.6,
            dewpoint_f: 34.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 5.8,
          },
          {
            time_epoch: 1741854600,
            time: "2025-03-13 12:00",
            temp_c: 18.4,
            temp_f: 65.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 341,
            wind_dir: "NNW",
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 32,
            cloud: 4,
            feelslike_c: 18.5,
            feelslike_f: 65.2,
            windchill_c: 18.5,
            windchill_f: 65.2,
            heatindex_c: 18.5,
            heatindex_f: 65.2,
            dewpoint_c: 1.4,
            dewpoint_f: 34.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 5.9,
          },
          {
            time_epoch: 1741858200,
            time: "2025-03-13 13:00",
            temp_c: 19.1,
            temp_f: 66.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 346,
            wind_dir: "NNW",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 30,
            cloud: 3,
            feelslike_c: 19.1,
            feelslike_f: 66.3,
            windchill_c: 19.1,
            windchill_f: 66.3,
            heatindex_c: 19.1,
            heatindex_f: 66.3,
            dewpoint_c: 1.1,
            dewpoint_f: 34,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 5.1,
          },
          {
            time_epoch: 1741861800,
            time: "2025-03-13 14:00",
            temp_c: 19.6,
            temp_f: 67.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 348,
            wind_dir: "NNW",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 28,
            cloud: 2,
            feelslike_c: 19.6,
            feelslike_f: 67.2,
            windchill_c: 19.6,
            windchill_f: 67.2,
            heatindex_c: 19.6,
            heatindex_f: 67.2,
            dewpoint_c: 0.8,
            dewpoint_f: 33.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 3.5,
          },
          {
            time_epoch: 1741865400,
            time: "2025-03-13 15:00",
            temp_c: 19.8,
            temp_f: 67.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 351,
            wind_dir: "N",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 27,
            cloud: 2,
            feelslike_c: 19.8,
            feelslike_f: 67.6,
            windchill_c: 19.8,
            windchill_f: 67.6,
            heatindex_c: 19.8,
            heatindex_f: 67.6,
            dewpoint_c: 0.5,
            dewpoint_f: 33,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.7,
            uv: 1.9,
          },
          {
            time_epoch: 1741869000,
            time: "2025-03-13 16:00",
            temp_c: 19.7,
            temp_f: 67.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 351,
            wind_dir: "N",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 27,
            cloud: 1,
            feelslike_c: 19.7,
            feelslike_f: 67.5,
            windchill_c: 19.7,
            windchill_f: 67.5,
            heatindex_c: 19.7,
            heatindex_f: 67.5,
            dewpoint_c: 0.3,
            dewpoint_f: 32.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 0.7,
          },
          {
            time_epoch: 1741872600,
            time: "2025-03-13 17:00",
            temp_c: 19.3,
            temp_f: 66.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 349,
            wind_dir: "N",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 19.3,
            feelslike_f: 66.8,
            windchill_c: 19.3,
            windchill_f: 66.8,
            heatindex_c: 19.3,
            heatindex_f: 66.8,
            dewpoint_c: 0.8,
            dewpoint_f: 33.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.2,
            gust_kph: 6.7,
            uv: 0.1,
          },
          {
            time_epoch: 1741876200,
            time: "2025-03-13 18:00",
            temp_c: 18.2,
            temp_f: 64.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 306,
            wind_dir: "NW",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 34,
            cloud: 0,
            feelslike_c: 18.2,
            feelslike_f: 64.7,
            windchill_c: 18.2,
            windchill_f: 64.7,
            heatindex_c: 18.2,
            heatindex_f: 64.7,
            dewpoint_c: 2,
            dewpoint_f: 35.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2,
            gust_kph: 3.2,
            uv: 0,
          },
          {
            time_epoch: 1741879800,
            time: "2025-03-13 19:00",
            temp_c: 17.6,
            temp_f: 63.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 197,
            wind_dir: "SSW",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 0,
            feelslike_c: 17.6,
            feelslike_f: 63.7,
            windchill_c: 17.6,
            windchill_f: 63.7,
            heatindex_c: 17.6,
            heatindex_f: 63.7,
            dewpoint_c: 2.3,
            dewpoint_f: 36.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.5,
            gust_kph: 4.1,
            uv: 0,
          },
          {
            time_epoch: 1741883400,
            time: "2025-03-13 20:00",
            temp_c: 17.1,
            temp_f: 62.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 185,
            wind_dir: "S",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 0,
            feelslike_c: 17.1,
            feelslike_f: 62.8,
            windchill_c: 17.1,
            windchill_f: 62.8,
            heatindex_c: 17.1,
            heatindex_f: 62.8,
            dewpoint_c: 2.1,
            dewpoint_f: 35.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.6,
            gust_kph: 7.4,
            uv: 0,
          },
          {
            time_epoch: 1741887000,
            time: "2025-03-13 21:00",
            temp_c: 16.6,
            temp_f: 61.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 198,
            wind_dir: "SSW",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 38,
            cloud: 0,
            feelslike_c: 16.6,
            feelslike_f: 61.8,
            windchill_c: 16.6,
            windchill_f: 61.8,
            heatindex_c: 16.6,
            heatindex_f: 61.8,
            dewpoint_c: 2.2,
            dewpoint_f: 36,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 0,
          },
          {
            time_epoch: 1741890600,
            time: "2025-03-13 22:00",
            temp_c: 15.9,
            temp_f: 60.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 223,
            wind_dir: "SW",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 39,
            cloud: 0,
            feelslike_c: 15.9,
            feelslike_f: 60.6,
            windchill_c: 15.9,
            windchill_f: 60.6,
            heatindex_c: 15.9,
            heatindex_f: 60.6,
            dewpoint_c: 2,
            dewpoint_f: 35.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.3,
            gust_kph: 7,
            uv: 0,
          },
          {
            time_epoch: 1741894200,
            time: "2025-03-13 23:00",
            temp_c: 15.3,
            temp_f: 59.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 243,
            wind_dir: "WSW",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 40,
            cloud: 0,
            feelslike_c: 15.3,
            feelslike_f: 59.6,
            windchill_c: 15.3,
            windchill_f: 59.6,
            heatindex_c: 15.3,
            heatindex_f: 59.6,
            dewpoint_c: 1.9,
            dewpoint_f: 35.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5,
            gust_kph: 8,
            uv: 0,
          },
        ],
      },
      {
        date: "2025-03-14",
        date_epoch: 1741910400,
        day: {
          maxtemp_c: 20.8,
          maxtemp_f: 69.4,
          mintemp_c: 11.9,
          mintemp_f: 53.5,
          avgtemp_c: 16.7,
          avgtemp_f: 62,
          maxwind_mph: 7.6,
          maxwind_kph: 12.2,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 32,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 1.4,
        },
        astro: {
          sunrise: "06:18 AM",
          sunset: "06:13 PM",
          moonrise: "06:27 PM",
          moonset: "06:19 AM",
          moon_phase: "Full Moon",
          moon_illumination: 100,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1741897800,
            time: "2025-03-14 00:00",
            temp_c: 14.7,
            temp_f: 58.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 262,
            wind_dir: "W",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 0,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 14.7,
            heatindex_f: 58.5,
            dewpoint_c: 1.6,
            dewpoint_f: 34.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9.1,
            uv: 0,
          },
          {
            time_epoch: 1741901400,
            time: "2025-03-14 01:00",
            temp_c: 14.3,
            temp_f: 57.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 278,
            wind_dir: "W",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 0,
            feelslike_c: 14.6,
            feelslike_f: 58.2,
            windchill_c: 14.6,
            windchill_f: 58.2,
            heatindex_c: 14.3,
            heatindex_f: 57.8,
            dewpoint_c: 1.1,
            dewpoint_f: 34,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7,
            gust_kph: 11.3,
            uv: 0,
          },
          {
            time_epoch: 1741905000,
            time: "2025-03-14 02:00",
            temp_c: 13.9,
            temp_f: 56.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 294,
            wind_dir: "WNW",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 40,
            cloud: 0,
            feelslike_c: 14,
            feelslike_f: 57.1,
            windchill_c: 14,
            windchill_f: 57.1,
            heatindex_c: 13.9,
            heatindex_f: 56.9,
            dewpoint_c: 0.7,
            dewpoint_f: 33.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12.1,
            uv: 0,
          },
          {
            time_epoch: 1741908600,
            time: "2025-03-14 03:00",
            temp_c: 13.2,
            temp_f: 55.8,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 297,
            wind_dir: "WNW",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 0,
            feelslike_c: 13.2,
            feelslike_f: 55.8,
            windchill_c: 13.2,
            windchill_f: 55.8,
            heatindex_c: 13.2,
            heatindex_f: 55.8,
            dewpoint_c: 0.3,
            dewpoint_f: 32.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12.1,
            uv: 0,
          },
          {
            time_epoch: 1741912200,
            time: "2025-03-14 04:00",
            temp_c: 12.7,
            temp_f: 54.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 290,
            wind_dir: "WNW",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 0,
            feelslike_c: 12.8,
            feelslike_f: 55,
            windchill_c: 12.8,
            windchill_f: 55,
            heatindex_c: 12.7,
            heatindex_f: 54.9,
            dewpoint_c: 0,
            dewpoint_f: 31.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.6,
            gust_kph: 10.6,
            uv: 0,
          },
          {
            time_epoch: 1741915800,
            time: "2025-03-14 05:00",
            temp_c: 12.2,
            temp_f: 54,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 42,
            cloud: 0,
            feelslike_c: 12.5,
            feelslike_f: 54.5,
            windchill_c: 12.5,
            windchill_f: 54.5,
            heatindex_c: 12.3,
            heatindex_f: 54.1,
            dewpoint_c: -0.2,
            dewpoint_f: 31.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9.1,
            uv: 0,
          },
          {
            time_epoch: 1741919400,
            time: "2025-03-14 06:00",
            temp_c: 11.9,
            temp_f: 53.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 284,
            wind_dir: "WNW",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 43,
            cloud: 0,
            feelslike_c: 12.3,
            feelslike_f: 54.1,
            windchill_c: 12.3,
            windchill_f: 54.1,
            heatindex_c: 12,
            heatindex_f: 53.5,
            dewpoint_c: -0.2,
            dewpoint_f: 31.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.2,
            gust_kph: 8.3,
            uv: 0,
          },
          {
            time_epoch: 1741923000,
            time: "2025-03-14 07:00",
            temp_c: 13.9,
            temp_f: 57.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 298,
            wind_dir: "WNW",
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 0,
            feelslike_c: 13.9,
            feelslike_f: 57.1,
            windchill_c: 13.9,
            windchill_f: 57.1,
            heatindex_c: 13.9,
            heatindex_f: 57.1,
            dewpoint_c: 1,
            dewpoint_f: 33.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.3,
            gust_kph: 5.3,
            uv: 0.5,
          },
          {
            time_epoch: 1741926600,
            time: "2025-03-14 08:00",
            temp_c: 15.9,
            temp_f: 60.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 338,
            wind_dir: "NNW",
            pressure_mb: 1021,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 33,
            cloud: 0,
            feelslike_c: 15.9,
            feelslike_f: 60.7,
            windchill_c: 15.9,
            windchill_f: 60.7,
            heatindex_c: 15.9,
            heatindex_f: 60.7,
            dewpoint_c: -0.3,
            dewpoint_f: 31.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.7,
            gust_kph: 2.8,
            uv: 1.6,
          },
          {
            time_epoch: 1741930200,
            time: "2025-03-14 09:00",
            temp_c: 16.9,
            temp_f: 62.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 28,
            wind_dir: "NNE",
            pressure_mb: 1021,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 31,
            cloud: 0,
            feelslike_c: 16.9,
            feelslike_f: 62.4,
            windchill_c: 16.9,
            windchill_f: 62.4,
            heatindex_c: 16.9,
            heatindex_f: 62.4,
            dewpoint_c: -0.4,
            dewpoint_f: 31.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.7,
            gust_kph: 4.3,
            uv: 3.2,
          },
          {
            time_epoch: 1741933800,
            time: "2025-03-14 10:00",
            temp_c: 17.8,
            temp_f: 64.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 43,
            wind_dir: "NE",
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 17.8,
            feelslike_f: 64.1,
            windchill_c: 17.8,
            windchill_f: 64.1,
            heatindex_c: 17.8,
            heatindex_f: 64.1,
            dewpoint_c: -0.5,
            dewpoint_f: 31.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.9,
            gust_kph: 6.2,
            uv: 4.8,
          },
          {
            time_epoch: 1741937400,
            time: "2025-03-14 11:00",
            temp_c: 18.8,
            temp_f: 65.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 54,
            wind_dir: "NE",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 18.8,
            feelslike_f: 65.9,
            windchill_c: 18.8,
            windchill_f: 65.9,
            heatindex_c: 18.8,
            heatindex_f: 65.9,
            dewpoint_c: -0.5,
            dewpoint_f: 31,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.7,
            uv: 6,
          },
          {
            time_epoch: 1741941000,
            time: "2025-03-14 12:00",
            temp_c: 19.5,
            temp_f: 67.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 61,
            wind_dir: "ENE",
            pressure_mb: 1020,
            pressure_in: 30.12,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 19.5,
            feelslike_f: 67.2,
            windchill_c: 19.5,
            windchill_f: 67.2,
            heatindex_c: 19.5,
            heatindex_f: 67.2,
            dewpoint_c: -0.8,
            dewpoint_f: 30.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.4,
            gust_kph: 10.4,
            uv: 6.2,
          },
          {
            time_epoch: 1741944600,
            time: "2025-03-14 13:00",
            temp_c: 20.1,
            temp_f: 68.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 61,
            wind_dir: "ENE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 24,
            cloud: 0,
            feelslike_c: 20.1,
            feelslike_f: 68.2,
            windchill_c: 20.1,
            windchill_f: 68.2,
            heatindex_c: 20.1,
            heatindex_f: 68.2,
            dewpoint_c: -1.1,
            dewpoint_f: 30.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.2,
            gust_kph: 9.9,
            uv: 5.3,
          },
          {
            time_epoch: 1741948200,
            time: "2025-03-14 14:00",
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 58,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 23,
            cloud: 0,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: -1.3,
            dewpoint_f: 29.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.2,
            gust_kph: 9.9,
            uv: 3.7,
          },
          {
            time_epoch: 1741951800,
            time: "2025-03-14 15:00",
            temp_c: 20.8,
            temp_f: 69.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 59,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 22,
            cloud: 0,
            feelslike_c: 20.8,
            feelslike_f: 69.4,
            windchill_c: 20.8,
            windchill_f: 69.4,
            heatindex_c: 20.8,
            heatindex_f: 69.4,
            dewpoint_c: -1.5,
            dewpoint_f: 29.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.6,
            uv: 2,
          },
          {
            time_epoch: 1741955400,
            time: "2025-03-14 16:00",
            temp_c: 20.7,
            temp_f: 69.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 62,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.05,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 22,
            cloud: 0,
            feelslike_c: 20.7,
            feelslike_f: 69.3,
            windchill_c: 20.7,
            windchill_f: 69.3,
            heatindex_c: 20.7,
            heatindex_f: 69.3,
            dewpoint_c: -1.7,
            dewpoint_f: 29,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8,
            gust_kph: 12.9,
            uv: 0.7,
          },
          {
            time_epoch: 1741959000,
            time: "2025-03-14 17:00",
            temp_c: 20.2,
            temp_f: 68.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 63,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.05,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 24,
            cloud: 0,
            feelslike_c: 20.2,
            feelslike_f: 68.4,
            windchill_c: 20.2,
            windchill_f: 68.4,
            heatindex_c: 20.2,
            heatindex_f: 68.4,
            dewpoint_c: -1,
            dewpoint_f: 30.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.2,
            uv: 0.1,
          },
          {
            time_epoch: 1741962600,
            time: "2025-03-14 18:00",
            temp_c: 18.8,
            temp_f: 65.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 57,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 28,
            cloud: 0,
            feelslike_c: 18.8,
            feelslike_f: 65.9,
            windchill_c: 18.8,
            windchill_f: 65.9,
            heatindex_c: 18.8,
            heatindex_f: 65.9,
            dewpoint_c: -0.2,
            dewpoint_f: 31.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.8,
            gust_kph: 17.5,
            uv: 0,
          },
          {
            time_epoch: 1741966200,
            time: "2025-03-14 19:00",
            temp_c: 18.1,
            temp_f: 64.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 55,
            wind_dir: "NE",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 18.1,
            feelslike_f: 64.5,
            windchill_c: 18.1,
            windchill_f: 64.5,
            heatindex_c: 18.1,
            heatindex_f: 64.5,
            dewpoint_c: -0.2,
            dewpoint_f: 31.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.1,
            gust_kph: 16.3,
            uv: 0,
          },
          {
            time_epoch: 1741969800,
            time: "2025-03-14 20:00",
            temp_c: 17.3,
            temp_f: 63.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 65,
            wind_dir: "ENE",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 30,
            cloud: 0,
            feelslike_c: 17.3,
            feelslike_f: 63.1,
            windchill_c: 17.3,
            windchill_f: 63.1,
            heatindex_c: 17.3,
            heatindex_f: 63.1,
            dewpoint_c: -0.3,
            dewpoint_f: 31.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 0,
          },
          {
            time_epoch: 1741973400,
            time: "2025-03-14 21:00",
            temp_c: 16.5,
            temp_f: 61.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 85,
            wind_dir: "E",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 32,
            cloud: 0,
            feelslike_c: 16.5,
            feelslike_f: 61.7,
            windchill_c: 16.5,
            windchill_f: 61.7,
            heatindex_c: 16.5,
            heatindex_f: 61.7,
            dewpoint_c: -0.3,
            dewpoint_f: 31.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 0,
          },
          {
            time_epoch: 1741977000,
            time: "2025-03-14 22:00",
            temp_c: 15.9,
            temp_f: 60.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 97,
            wind_dir: "E",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 33,
            cloud: 0,
            feelslike_c: 15.9,
            feelslike_f: 60.5,
            windchill_c: 15.9,
            windchill_f: 60.5,
            heatindex_c: 15.9,
            heatindex_f: 60.5,
            dewpoint_c: -0.3,
            dewpoint_f: 31.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.8,
            gust_kph: 14.1,
            uv: 0,
          },
          {
            time_epoch: 1741980600,
            time: "2025-03-14 23:00",
            temp_c: 15.3,
            temp_f: 59.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 100,
            wind_dir: "E",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 35,
            cloud: 0,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 15.3,
            heatindex_f: 59.5,
            dewpoint_c: 0,
            dewpoint_f: 31.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.5,
            uv: 0,
          },
        ],
      },
      {
        date: "2025-03-15",
        date_epoch: 1741996800,
        day: {
          maxtemp_c: 21.6,
          maxtemp_f: 70.9,
          mintemp_c: 11.7,
          mintemp_f: 53,
          avgtemp_c: 17,
          avgtemp_f: 62.5,
          maxwind_mph: 10.7,
          maxwind_kph: 17.3,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 29,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 1.5,
        },
        astro: {
          sunrise: "06:17 AM",
          sunset: "06:14 PM",
          moonrise: "07:24 PM",
          moonset: "06:42 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: 100,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1741984200,
            time: "2025-03-15 00:00",
            temp_c: 14.7,
            temp_f: 58.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 102,
            wind_dir: "ESE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 0,
            feelslike_c: 15,
            feelslike_f: 59,
            windchill_c: 15,
            windchill_f: 59,
            heatindex_c: 14.7,
            heatindex_f: 58.4,
            dewpoint_c: -0.1,
            dewpoint_f: 31.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7,
            gust_kph: 11.3,
            uv: 0,
          },
          {
            time_epoch: 1741987800,
            time: "2025-03-15 01:00",
            temp_c: 14.1,
            temp_f: 57.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 103,
            wind_dir: "ESE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 37,
            cloud: 0,
            feelslike_c: 14.4,
            feelslike_f: 57.9,
            windchill_c: 14.4,
            windchill_f: 57.9,
            heatindex_c: 14.1,
            heatindex_f: 57.4,
            dewpoint_c: -0.2,
            dewpoint_f: 31.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.6,
            gust_kph: 10.6,
            uv: 0,
          },
          {
            time_epoch: 1741991400,
            time: "2025-03-15 02:00",
            temp_c: 13.5,
            temp_f: 56.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 96,
            wind_dir: "E",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 39,
            cloud: 0,
            feelslike_c: 13.9,
            feelslike_f: 57,
            windchill_c: 13.9,
            windchill_f: 57,
            heatindex_c: 13.5,
            heatindex_f: 56.3,
            dewpoint_c: -0.1,
            dewpoint_f: 31.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9.1,
            uv: 0,
          },
          {
            time_epoch: 1741995000,
            time: "2025-03-15 03:00",
            temp_c: 12.9,
            temp_f: 55.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 78,
            wind_dir: "ENE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 40,
            cloud: 0,
            feelslike_c: 13.5,
            feelslike_f: 56.3,
            windchill_c: 13.5,
            windchill_f: 56.3,
            heatindex_c: 13,
            heatindex_f: 55.3,
            dewpoint_c: -0.2,
            dewpoint_f: 31.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 0,
          },
          {
            time_epoch: 1741998600,
            time: "2025-03-15 04:00",
            temp_c: 12.5,
            temp_f: 54.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 68,
            wind_dir: "ENE",
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 0,
            feelslike_c: 13,
            feelslike_f: 55.4,
            windchill_c: 13,
            windchill_f: 55.4,
            heatindex_c: 12.5,
            heatindex_f: 54.4,
            dewpoint_c: -0.4,
            dewpoint_f: 31.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 0,
          },
          {
            time_epoch: 1742002200,
            time: "2025-03-15 05:00",
            temp_c: 12,
            temp_f: 53.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 52,
            wind_dir: "NE",
            pressure_mb: 1020,
            pressure_in: 30.12,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 42,
            cloud: 0,
            feelslike_c: 12,
            feelslike_f: 53.5,
            windchill_c: 12,
            windchill_f: 53.5,
            heatindex_c: 12,
            heatindex_f: 53.5,
            dewpoint_c: -0.6,
            dewpoint_f: 30.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6,
            uv: 0,
          },
          {
            time_epoch: 1742005800,
            time: "2025-03-15 06:00",
            temp_c: 11.7,
            temp_f: 53,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 16,
            wind_dir: "NNE",
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 42,
            cloud: 0,
            feelslike_c: 11.7,
            feelslike_f: 53,
            windchill_c: 11.7,
            windchill_f: 53,
            heatindex_c: 11.7,
            heatindex_f: 53,
            dewpoint_c: -0.6,
            dewpoint_f: 30.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.8,
            gust_kph: 4.5,
            uv: 0,
          },
          {
            time_epoch: 1742009400,
            time: "2025-03-15 07:00",
            temp_c: 13.6,
            temp_f: 56.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 12,
            wind_dir: "NNE",
            pressure_mb: 1021,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 40,
            cloud: 0,
            feelslike_c: 13.6,
            feelslike_f: 56.6,
            windchill_c: 13.6,
            windchill_f: 56.6,
            heatindex_c: 13.6,
            heatindex_f: 56.6,
            dewpoint_c: 0.2,
            dewpoint_f: 32.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.3,
            gust_kph: 3.8,
            uv: 0.5,
          },
          {
            time_epoch: 1742013000,
            time: "2025-03-15 08:00",
            temp_c: 15.5,
            temp_f: 59.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 349,
            wind_dir: "N",
            pressure_mb: 1022,
            pressure_in: 30.17,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 32,
            cloud: 2,
            feelslike_c: 15.5,
            feelslike_f: 59.9,
            windchill_c: 15.5,
            windchill_f: 59.9,
            heatindex_c: 15.5,
            heatindex_f: 59.9,
            dewpoint_c: -1.1,
            dewpoint_f: 30,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.4,
            gust_kph: 2.3,
            uv: 1.7,
          },
          {
            time_epoch: 1742016600,
            time: "2025-03-15 09:00",
            temp_c: 16.6,
            temp_f: 61.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 35,
            wind_dir: "NE",
            pressure_mb: 1022,
            pressure_in: 30.18,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 29,
            cloud: 0,
            feelslike_c: 16.6,
            feelslike_f: 61.8,
            windchill_c: 16.6,
            windchill_f: 61.8,
            heatindex_c: 16.6,
            heatindex_f: 61.8,
            dewpoint_c: -1.4,
            dewpoint_f: 29.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.9,
            gust_kph: 4.6,
            uv: 3.3,
          },
          {
            time_epoch: 1742020200,
            time: "2025-03-15 10:00",
            temp_c: 17.7,
            temp_f: 63.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 58,
            wind_dir: "ENE",
            pressure_mb: 1022,
            pressure_in: 30.17,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 27,
            cloud: 0,
            feelslike_c: 17.7,
            feelslike_f: 63.9,
            windchill_c: 17.7,
            windchill_f: 63.9,
            heatindex_c: 17.7,
            heatindex_f: 63.9,
            dewpoint_c: -1.7,
            dewpoint_f: 29,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.4,
            gust_kph: 7.1,
            uv: 5.1,
          },
          {
            time_epoch: 1742023800,
            time: "2025-03-15 11:00",
            temp_c: 18.9,
            temp_f: 66.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 67,
            wind_dir: "ENE",
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 25,
            cloud: 0,
            feelslike_c: 18.9,
            feelslike_f: 66.1,
            windchill_c: 18.9,
            windchill_f: 66.1,
            heatindex_c: 18.9,
            heatindex_f: 66.1,
            dewpoint_c: -1.7,
            dewpoint_f: 28.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12,
            uv: 6.2,
          },
          {
            time_epoch: 1742027400,
            time: "2025-03-15 12:00",
            temp_c: 20,
            temp_f: 68.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 74,
            wind_dir: "ENE",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 23,
            cloud: 0,
            feelslike_c: 20,
            feelslike_f: 68.1,
            windchill_c: 20,
            windchill_f: 68.1,
            heatindex_c: 20,
            heatindex_f: 68.1,
            dewpoint_c: -1.8,
            dewpoint_f: 28.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 6.4,
          },
          {
            time_epoch: 1742031000,
            time: "2025-03-15 13:00",
            temp_c: 20.9,
            temp_f: 69.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 74,
            wind_dir: "ENE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 21,
            cloud: 0,
            feelslike_c: 20.9,
            feelslike_f: 69.6,
            windchill_c: 20.9,
            windchill_f: 69.6,
            heatindex_c: 20.9,
            heatindex_f: 69.6,
            dewpoint_c: -2,
            dewpoint_f: 28.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 5.5,
          },
          {
            time_epoch: 1742034600,
            time: "2025-03-15 14:00",
            temp_c: 21.5,
            temp_f: 70.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 72,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 20,
            cloud: 0,
            feelslike_c: 21.5,
            feelslike_f: 70.7,
            windchill_c: 21.5,
            windchill_f: 70.7,
            heatindex_c: 21.8,
            heatindex_f: 71.3,
            dewpoint_c: -2.6,
            dewpoint_f: 27.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.1,
            gust_kph: 17.8,
            uv: 3.8,
          },
          {
            time_epoch: 1742038200,
            time: "2025-03-15 15:00",
            temp_c: 21.6,
            temp_f: 70.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 72,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 19,
            cloud: 5,
            feelslike_c: 21.6,
            feelslike_f: 70.9,
            windchill_c: 21.6,
            windchill_f: 70.9,
            heatindex_c: 21.9,
            heatindex_f: 71.4,
            dewpoint_c: -3.3,
            dewpoint_f: 26.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.3,
            gust_kph: 19.9,
            uv: 2,
          },
          {
            time_epoch: 1742041800,
            time: "2025-03-15 16:00",
            temp_c: 21.4,
            temp_f: 70.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 72,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 18,
            cloud: 10,
            feelslike_c: 21.4,
            feelslike_f: 70.5,
            windchill_c: 21.4,
            windchill_f: 70.5,
            heatindex_c: 21.8,
            heatindex_f: 71.2,
            dewpoint_c: -4,
            dewpoint_f: 24.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.4,
            gust_kph: 18.3,
            uv: 0.7,
          },
          {
            time_epoch: 1742045400,
            time: "2025-03-15 17:00",
            temp_c: 20.9,
            temp_f: 69.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 61,
            wind_dir: "ENE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 20,
            cloud: 15,
            feelslike_c: 20.9,
            feelslike_f: 69.5,
            windchill_c: 20.9,
            windchill_f: 69.5,
            heatindex_c: 20.9,
            heatindex_f: 69.5,
            dewpoint_c: -2.9,
            dewpoint_f: 26.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.1,
            gust_kph: 17.8,
            uv: 0.1,
          },
          {
            time_epoch: 1742049000,
            time: "2025-03-15 18:00",
            temp_c: 19.4,
            temp_f: 67,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 53,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 22,
            cloud: 33,
            feelslike_c: 19.4,
            feelslike_f: 67,
            windchill_c: 19.4,
            windchill_f: 67,
            heatindex_c: 19.4,
            heatindex_f: 67,
            dewpoint_c: -2.5,
            dewpoint_f: 27.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 0,
          },
          {
            time_epoch: 1742052600,
            time: "2025-03-15 19:00",
            temp_c: 18.7,
            temp_f: 65.7,
            is_day: 0,
            condition: {
              text: "Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 52,
            wind_dir: "NE",
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 24,
            cloud: 86,
            feelslike_c: 18.7,
            feelslike_f: 65.7,
            windchill_c: 18.7,
            windchill_f: 65.7,
            heatindex_c: 18.7,
            heatindex_f: 65.7,
            dewpoint_c: -2.4,
            dewpoint_f: 27.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.4,
            gust_kph: 20,
            uv: 0,
          },
          {
            time_epoch: 1742056200,
            time: "2025-03-15 20:00",
            temp_c: 18.1,
            temp_f: 64.6,
            is_day: 0,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 58,
            wind_dir: "ENE",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 25,
            cloud: 95,
            feelslike_c: 18.1,
            feelslike_f: 64.6,
            windchill_c: 18.1,
            windchill_f: 64.6,
            heatindex_c: 18.1,
            heatindex_f: 64.6,
            dewpoint_c: -2.1,
            dewpoint_f: 28.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 0,
          },
          {
            time_epoch: 1742059800,
            time: "2025-03-15 21:00",
            temp_c: 17.5,
            temp_f: 63.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 73,
            wind_dir: "ENE",
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 27,
            cloud: 5,
            feelslike_c: 17.5,
            feelslike_f: 63.6,
            windchill_c: 17.5,
            windchill_f: 63.6,
            heatindex_c: 17.5,
            heatindex_f: 63.6,
            dewpoint_c: -1.8,
            dewpoint_f: 28.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.7,
            gust_kph: 12.4,
            uv: 0,
          },
          {
            time_epoch: 1742063400,
            time: "2025-03-15 22:00",
            temp_c: 17,
            temp_f: 62.5,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 94,
            wind_dir: "E",
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 28,
            cloud: 6,
            feelslike_c: 17,
            feelslike_f: 62.5,
            windchill_c: 17,
            windchill_f: 62.5,
            heatindex_c: 17,
            heatindex_f: 62.5,
            dewpoint_c: -1.8,
            dewpoint_f: 28.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.2,
            uv: 0,
          },
          {
            time_epoch: 1742067000,
            time: "2025-03-15 23:00",
            temp_c: 16.5,
            temp_f: 61.7,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 94,
            wind_dir: "E",
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 28,
            cloud: 6,
            feelslike_c: 16.5,
            feelslike_f: 61.7,
            windchill_c: 16.5,
            windchill_f: 61.7,
            heatindex_c: 16.5,
            heatindex_f: 61.7,
            dewpoint_c: -2.2,
            dewpoint_f: 28.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.2,
            gust_kph: 13.1,
            uv: 0,
          },
        ],
      },
    ],
  },
};
